### ISSUE TITLE
Maybe a Bug: Missing Feature Normalize in VoxelNet

### ISSUE THREAD

**Issue by BoPang1996** [valeoai/SLidR#24] opened 2022-10-15 06:45 UTC
Maybe a bug: the output feature is not normalized for NCE Loss, which exists in MinkUNet [code](https://github.com/valeoai/SLidR/blob/f7d36765ebb4fb1c2580233e5ef3615cc69a644f/model/res16unet.py#L285).

**Comment by CSautier** [comment] 2022-10-17 09:36
You are right, that is indeed not right. I pushed a fix for now. As I mentionned in issue #22 there are a multiple issues with the VoxelNet experiment (which wasn't part of the published article), that I intend to fix in the future.

**Comment by BoPang1996** [comment] 2022-10-24 06:04
should be "sp_tensor._features" not "sp_tensor.features"

**Comment by CSautier** [comment] 2022-11-22 13:28
The problem is solved by switching to spconv2

**Closed as completed by CSautier** 2022-11-22 13:28 UTC
